[package]
name = "commit-lint"
version = "0.1.0"
authors = ["Johannes Sch√∂pp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"